#!/usr/bin/env bash
echo 'O P E R A Ç Õ E S  R E L A C I O N A I S COM AWK'
echo '-----------------------------------------------------------'
echo '1) Operandos numéricos literais definidos em design-time:'
echo -n "awk 'BEGIN {print 2 == 3}' = "; awk 'BEGIN {print 2 == 3}'
echo -n "awk 'BEGIN {print 2 != 3}' = "; awk 'BEGIN {print 2 != 3}'
echo -n "awk 'BEGIN {print 2 < 3}' = "; awk 'BEGIN {print 2 < 3}'
echo -n "awk 'BEGIN {print 2 <= 3}' = "; awk 'BEGIN {print 2 <= 3}'
echo -n "awk 'BEGIN {print (2 > 3)}' = "; awk 'BEGIN {print (2 > 3)}'
echo -n "awk 'BEGIN {print (2 >= 3)}' = "; awk 'BEGIN {print (2 >= 3)}'
echo '-----------------------------------------------------------'
echo -n "awk 'BEGIN {var1=2; var2=3; print var1 == var2}' = "; awk 'BEGIN {var1=2; var2=3; print var1 == var2}'
echo -n "NOVÍSSIMA: awk '{var1=2; var2=3; print var1 == var2}' <<< ''= "; awk '{var1=2; var2=3; print var1 == var2}' <<< ''
echo -n "awk -v var1=2 -v var2=3 'BEGIN {print var1 == var2}' = "; awk -v var1=2 -v var2=3 'BEGIN {print var1 == var2}'
echo -n "NOVA: awk -v var1=2 -v var2=3 '{print var1 == var2}' <<< '' = "; awk -v var1=2 -v var2=3 '{print var1 == var2}' <<< ''		#relacional2_awk
echo '-----------------------------------------------------------'
echo -n "NOVÍSSIMA: echo '' | awk '{var1=2; var2=3; print var1 == var2}' = "; echo '' | awk '{var1=2; var2=3; print var1 == var2}'
echo -n "echo | awk '{var1=2; var2=3; print var1 == var2}' = "; echo | awk '{var1=2; var2=3; print var1 == var2}'
echo -n "NOVA: echo '' | awk -v var1=2 -v var2=3 '{print var1 == var2}' = "; echo '' | awk -v var1=2 -v var2=3 '{print var1 == var2}'	#relacional2_awk
echo -n "echo | awk -v var1=2 -v var2=3 '{print var1 == var2}'  = "; echo | awk -v var1=2 -v var2=3 '{print var1 == var2}' 
echo '-----------------------------------------------------------'
echo -n "awk '{print \$1 == \$2}' <<< '2 3' = "; awk '{print $1 == $2}' <<< '2 3'
echo -n "awk '{print 2 == 3}' <<< '' = "; awk '{print 2 == 3}' <<< ''
echo -n "echo '2 3' | awk '{print \$1 == \$2}' = "; echo '2 3' | awk '{print $1 == $2}'
echo -n "echo '' | awk '{print 2 == 3}' = "; echo '' | awk '{print 2 == 3}'
echo -n "echo | awk '{print 2 == 3}' = "; echo | awk '{print 2 == 3}'
echo '-----------------------------------------------------------'
echo '2) Operandos numéricos variáveis definidos em design-time:'
echo 'a=2;b=3';a=2;b=3
echo -n "awk 'BEGIN {print '\$a' == '\$b'}' = "; awk 'BEGIN {print '$a' == '$b'}'
#echo 'Para os outros operadores, ver Observações
echo '-----------------------------------------------------------'
echo -n "awk 'BEGIN {var1='\$a'; var2='\$b'; print var1 == var2}' = "; awk 'BEGIN {var1='$a'; var2='$b'; print var1 == var2}'
echo -n "NOVÍSSIMA: awk '{var1='\$a'; var2='\$b'; print var1 == var2}' <<< ''= "; awk '{var1='$a'; var2='$b'; print var1 == var2}' <<< ''
echo -n "awk -v var1=\$a -v var2=\$b 'BEGIN {print var1 == var2}' = "; awk -v var1=$a -v var2=$b 'BEGIN {print var1 == var2}'
echo -n "NOVA: awk -v var1=\$a -v var2=\$b '{print var1 == var2}' <<< '' = "; awk -v var1=$a -v var2=$b '{print var1 == var2}' <<< ''		#relacional2_awk	
echo '-----------------------------------------------------------'
echo -n "NOVÍSSIMA: echo '' | awk '{var1='\$a'; var2='\$b'; print var1 == var2}' = "; echo '' | awk '{var1='$a'; var2='$b'; print var1 == var2}'
echo -n "echo | awk '{var1='\$a'; var2='\$b'; print var1 == var2}' = "; echo | awk '{var1='$a'; var2='$b'; print var1 == var2}'
echo -n "NOVA: echo '' | awk -v var1=\$a -v var2=\$b '{print var1 == var2}' = "; echo '' | awk -v var1=$a -v var2=$b '{print var1 == var2}'	#relacional2_awk
echo -n "echo | awk -v var1=\$a -v var2=\$b '{print var1 == var2}' = "; echo | awk -v var1=$a -v var2=$b '{print var1 == var2}'
echo '-----------------------------------------------------------'
echo -n "awk '{print \$1 == \$2}' <<< \"\$a \$b\" = "; awk '{print $1 == $2}' <<< "$a $b"
echo -n "awk 'BEGIN {print '\$a' == '\$b'}' <<< '' = "; awk 'BEGIN {print '$a' == '$b'}' <<< ''
echo -n "echo \"\$a \$b\" | awk '{print \$1 == \$2}' = "; echo "$a $b" | awk '{print $1 == $2}'
echo -n "echo '' | awk '{print '\$a' == '\$b'}' = "; echo '' | awk '{print '$a' == '$b'}'
echo -n "echo | awk '{print '\$a' == '\$b'}' = "; echo | awk '{print '$a' == '$b'}'

#echo 'OBSERVAÇÕES:'
#echo '- No awk, variáveis não inicializadas são tratadas como zero (em contextos numéricos)'
#echo '  ou como string vazia (em contextos de texto). Isso pode levar a comparações'
#echo '  inesperadas sem gerar erros.'
#echo '- Exemplo: var1=2; var3 não definida => var1 == var3 avalia 2 == 0, que é false.'
#echo 'Explicar por que expressões com > e >= precisam estar dentro de parênteses após comando print!!!'

