#!/usr/bin/env bash
echo -e "COMANDO\t\tSAÍDA\t\t\t\tOBSERVAÇÃO"
echo "Wrappers:"
echo "* Aspas duplas"
echo -e "\"\t\t>\t\t\t\tAguarda fechamento com \"\n""\t\t: comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo -e "\"\"\t\tComando '' não encontrado, mas poder ser instalado com: ..."
echo "------------------------------------------------------------------------------------------"
echo -e "\"a\"\t\ta: comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo -e "\"'a'\"\t\t'a': comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo -e "\"\`a\`\"\t\ta: comando não encontrado\n""\t\tComando '' não encontrado, mas poder ser instalado com: ..."
echo "------------------------------------------------------------------------------------------"
echo -e "\"x\`a\`y\"\t\txy: comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo "* Aspas simples"
echo -e "'\t\t>\t\t\t\tAguarda fechamento com '\n""\t\t: comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo -e "''\t\tComando '' não encontrado, mas poder ser instalado com: ..."
echo "------------------------------------------------------------------------------------------"
echo -e "'a'\t\ta: comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo -e "'\"a\"'\t\t\"a\": comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo -e "'\`a\`'\t\t\`a\`: comando não encontrado"
echo "------------------------------------------------------------------------------------------"
echo "Substituição de comandos:"
echo "* Acentos graves (crases, backticks)"
echo -e "\`\t\t>\t\t\t\tAguarda fechamento com \` e nada é impresso"
echo "------------------------------------------------------------------------------------------"
echo -e "\`\`\t\t\t\t\t\tNada é impresso; equivale a \$()"
echo "------------------------------------------------------------------------------------------"
echo -e "\`a\`\t\ta: comando não encontrado\tEquivale a \$(a)"
echo "------------------------------------------------------------------------------------------"
echo -e "\`\"a\"\`\t\ta: comando não encontrado\tEquivale a \$(\"a\")"
echo "------------------------------------------------------------------------------------------"
echo -e "\`'a'\`\t\ta: comando não encontrado\tEquivale a \$('a')"
echo "------------------------------------------------------------------------------------------"
#echo -e "Este script mostra exemplos de como o Bash reage a diferentes invólucros."
#echo -e "Copie e cole os comandos da coluna COMANDO em seu terminal para testar"
#echo "------------------------------------------------------------------------------------------"
#echo "Invólucros \"\" '' \`\`"
#echo "Sobre os invólucros "", '' e \`\`"	entre aspas duplas, aspas duplas devem ser escapadas com \ (para serem mostradas)
#echo "Sobre os invólucros \"\", '' e ``"	entre aspas duplas, acento grave (crase) deve se escapado com \ (para ser mostrado)	
#echo 'Sobre os invólucros "", '' e ``'		#entre aspas simples, tudo é literal (exceto aspas simples, que se presentes indicam outra string ou se única gera erro)
#echo -e "a\t\ta: comando não encontrado"

